# Generated by Django 4.0.2 on 2022-02-19 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dica', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('onde_assistir', models.CharField(max_length=200)),
                ('nota_de_avaliacao', models.CharField(max_length=200)),
                ('date_da_dica', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
