# Generated by Django 4.0.2 on 2022-02-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('dicas', '0002_dica_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='dica',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
            preserve_default=False,
        ),
    ]
