# Generated by Django 4.0.2 on 2022-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicas', '0004_dica_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dica',
            name='foto_dica',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
